Repository acmucsd/membership-portal-ui-v2, pull requests merged in 2023-04, with the labels that each got.

#7 Navbar Redesign (Desktop Only)
  package.json
  public/assets/icons/profile-icon.svg
  public/assets/icons/shop-icon.svg
  src/components/auth/SignInButton/index.tsx
  src/components/layout/ContentView/index.tsx
  src/components/layout/ContentView/style.module.scss
  src/components/layout/ContentView/style.module.scss.d.ts
  src/components/layout/Navbar/index.tsx
  src/components/layout/Navbar/style.module.scss
  src/components/layout/Navbar/style.module.scss.d.ts
  src/components/layout/PageHeader/index.tsx
  src/components/layout/PageHeader/style.module.scss
  src/components/layout/PageHeader/style.module.scss.d.ts
  src/components/layout/PageLayout/index.tsx
  src/components/layout/PageLayout/style.module.scss
  src/components/layout/PageLayout/style.module.scss.d.ts
  src/components/layout/index.ts
  src/styles/globals.scss
  yarn.lock
Labels: enhancement, PR: Needs Review

#11 Finish registration flow
  .eslintrc.json
  next.config.js
  src/lib/api/AuthAPI.ts
  src/lib/config.ts
  src/lib/managers/AuthManager.ts
  src/lib/types/apiRequests.d.ts
  src/pages/404.tsx
  src/pages/check-email.tsx
  src/pages/logout.tsx
  src/pages/register.tsx
  src/pages/verify-email/[accessCode].tsx
  src/styles/pages/check-email.module.scss
  src/styles/pages/check-email.module.scss.d.ts
  src/styles/pages/verify-email.module.scss
  src/styles/pages/verify-email.module.scss.d.ts
Labels: PR: Needs Review

#12 Implemented page redirection for logged out users
  src/lib/hoc/withAccessType.ts
  src/pages/login.tsx
Labels: PR: Needs Review

#8 Configure Cypress for local UI testing
  .eslintrc.json
  cypress.config.ts
  cypress/e2e/pages/auth/login.cy.ts
  cypress/fixtures/accounts.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/tsconfig.json
  package.json
  yarn.lock
Labels: help wanted, PR: Good to Merge

#15 Completed Reset Password Page
  src/components/auth/SignInFormItem/index.tsx
  src/lib/api/AuthAPI.ts
  src/lib/managers/AuthManager.ts
  src/lib/types/apiRequests.d.ts
  src/pages/forgot-password.tsx
  src/pages/login.tsx
  src/pages/register.tsx
  src/pages/reset-password/[accessCode].tsx
Labels: enhancement, PR: Needs Review

#16 Add Pull Request Template
  .github/pull_request_template.md
  .github/workflows/label_ready_pr_to_merge.yml
Labels: documentation, enhancement, PR: Needs Review, PR: Good to Merge

#17 Add Validation Service
  src/lib/services/ValidationService.ts
  src/pages/forgot-password.tsx
  src/pages/login.tsx
  src/pages/register.tsx
  src/pages/reset-password/[accessCode].tsx
Labels: enhancement, PR: Needs Review, Code Quality

#22 Fix exports for code quality
  src/lib/api/index.ts
  src/lib/index.ts
  src/lib/managers/index.ts
  src/lib/services/index.ts
Labels: PR: Needs Review

#23 Optimize Images
  src/components/layout/Navbar/index.tsx
  src/pages/404.tsx
Labels: enhancement, PR: Needs Review, PR: Good to Merge

#24 Optimize Fonts
  src/components/auth/SignInButton/style.module.scss
  src/pages/_app.tsx
  src/styles/globals.scss
Labels: enhancement, PR: Needs Review, PR: Good to Merge

#25 Implement SEO
  next.config.js
  src/components/common/SEO/index.tsx
  src/components/common/index.ts
  src/components/layout/DarkModeToggle/index.tsx
  src/pages/_app.tsx
Labels: PR: Needs Review, PR: Good to Merge

#27 Implement user handle routes
  src/lib/api/UserAPI.ts
  src/lib/config.ts
  src/pages/u/[handle].tsx
Labels: PR: Needs Review, PR: Good to Merge

#26 Fix Redirect Links
  src/lib/hoc/withAccessType.ts
  src/lib/services/PermissionService.ts
  src/pages/admin.tsx
Labels: PR: Needs Review, PR: Good to Merge
