Repository acmucsd/membership-portal-ui-v2, pull requests merged in 2023-10, with the labels that each got.

#73 Upgrade dependencies (fix failing CircleCI lint test)
  package.json
  src/styles/themes.scss
  yarn.lock
Labels: Bug, PR: Needs Review, PR: Good to Merge, High Priority, dependencies

#34 Admin Event Management Tools
  .env.example
  .eslintrc.json
  next.config.js
  package.json
  public/assets/icons/setting-icon.svg
  src/components/admin/event/EventDetailsForm/index.tsx
  src/components/admin/event/EventDetailsForm/style.module.scss
  src/components/admin/event/EventDetailsForm/style.module.scss.d.ts
  src/components/admin/event/EventDetailsFormItem/index.tsx
  src/components/admin/event/EventDetailsFormItem/style.module.scss
  src/components/admin/event/EventDetailsFormItem/style.module.scss.d.ts
  src/components/admin/event/ManageEventCard/index.tsx
  src/components/admin/event/ManageEventCard/style.module.scss
  src/components/admin/event/ManageEventCard/style.module.scss.d.ts
  src/components/admin/event/NotionAutofill/index.tsx
  src/components/admin/event/NotionAutofill/style.module.scss
  src/components/admin/event/NotionAutofill/style.module.scss.d.ts
  src/components/admin/event/index.tsx
  src/components/common/Button/index.tsx
  src/components/common/Button/style.module.scss
  src/components/common/Button/style.module.scss.d.ts
  src/components/layout/Navbar/index.tsx
  src/lib/api/EventAPI.ts
  src/lib/api/KlefkiAPI.ts
  src/lib/api/UserAPI.ts
  src/lib/api/index.ts
  src/lib/config.ts
  src/lib/managers/AdminEventManager.ts
  src/lib/managers/EventManager.ts
  src/lib/managers/index.ts
  src/lib/services/PermissionService.ts
  src/lib/showToast.tsx
  src/lib/types/apiRequests.d.ts
  src/lib/types/apiResponses.d.ts
  src/lib/utils.ts
  src/pages/admin/event/create.tsx
  src/pages/admin/event/edit/[uuid].tsx
  src/pages/admin/event/index.tsx
  src/pages/admin/index.tsx
  src/styles/pages/manage-events.module.scss
  src/styles/pages/manage-events.module.scss.d.ts
  yarn.lock
Labels: Enhancement, PR: Needs Review, PR: Good to Merge

#76 Andy/three toggle dark mode
  public/assets/icons/monitor.svg
  public/assets/icons/moon.svg
  public/assets/icons/sun.svg
  src/components/common/ThemeToggle/index.tsx
  src/components/common/ThemeToggle/style.module.scss
  src/components/common/ThemeToggle/style.module.scss.d.ts
  src/components/layout/DarkModeToggle/index.tsx
  src/components/layout/Navbar/index.tsx
  src/components/layout/Navbar/style.module.scss
  src/styles/themes.scss
  src/styles/vars.scss
  yarn.lock
Labels: PR: Good to Merge
