Repository acmucsd/membership-portal-ui-v2, pull requests merged in 2024-01, with the labels that each got.

#105 Make compatible with multiple store gallery images
  src/components/store/CollectionSlider/index.tsx
  src/lib/types/apiRequests.d.ts
  src/lib/types/apiResponses.d.ts
  src/lib/utils.ts
  src/pages/store/index.tsx
Labels: PR: Needs Review, PR: Good to Merge

#106 Fix image rendering for orders page
  src/components/store/OrderSummary/index.tsx
  src/lib/types/apiResponses.d.ts
Labels: PR: Needs Review, PR: Good to Merge

#107 Events Page/Card: Fix some stuff
  src/components/events/EventCard/index.tsx
  src/components/events/EventCard/style.module.scss
  src/components/events/EventDisplay/index.tsx
  src/components/events/EventModal/style.module.scss
  src/pages/events.tsx
Labels: PR: Needs Review, PR: Good to Merge

#109 Delete label_ready_pr_to_merge.yml
  .github/workflows/label_ready_pr_to_merge.yml
Labels: PR: Needs Review

#112 Finish main page hero
  public/assets/graphics/portal/raccoon-hero.svg
  public/assets/graphics/portal/waves.svg
  public/assets/icons/check-mark.svg
  public/assets/icons/info-icon.svg
  public/assets/icons/leaderboard-icon.svg
  public/assets/icons/shop-icon.svg
  src/components/common/Typography/index.tsx
  src/components/events/EventCarousel/index.tsx
  src/components/home/Hero/index.tsx
  src/components/home/Hero/style.module.scss
  src/components/home/Hero/style.module.scss.d.ts
  src/components/layout/Navbar/index.tsx
  src/components/layout/Navbar/style.module.scss
  src/lib/api/EventAPI.ts
  src/lib/managers/EventManager.ts
  src/pages/checkin.tsx
  src/pages/index.tsx
  src/styles/pages/Home.module.scss
Labels: PR: Needs Review

#91 Edit profile page
  .eslintrc.json
  public/assets/icons/devpost-icon.svg
  public/assets/icons/download-icon.svg
  public/assets/icons/dropdown-arrow-1.svg
  src/components/admin/event/EventDetailsForm/index.tsx
  src/components/admin/event/NotionAutofill/index.tsx
  src/components/common/Cropper/index.tsx
  src/components/common/Cropper/style.module.scss
  src/components/common/Cropper/style.module.scss.d.ts
  src/components/common/Dropdown/index.tsx
  src/components/common/Modal/index.tsx
  src/components/common/Modal/style.module.scss
  src/components/common/Modal/style.module.scss.d.ts
  src/components/common/PaginationControls/index.tsx
  src/components/common/index.ts
  src/components/events/CalendarButtons/index.tsx
  src/components/events/EventModal/index.tsx
  src/components/events/EventModal/style.module.scss
  src/components/events/EventModal/style.module.scss.d.ts
  src/components/layout/Navbar/index.tsx
  src/components/layout/PageLayout/style.module.scss
  src/components/profile/EditField/index.tsx
  src/components/profile/EditField/style.module.scss
  src/components/profile/EditField/style.module.scss.d.ts
  src/components/profile/Preview/index.tsx
  src/components/profile/Preview/style.module.scss
  src/components/profile/Preview/style.module.scss.d.ts
  src/components/profile/SocialMediaIcon/index.tsx
  src/components/profile/SocialMediaIcon/style.module.scss
  src/components/profile/SocialMediaIcon/style.module.scss.d.ts
  src/components/profile/Switch/index.tsx
  src/components/profile/Switch/style.module.scss
  src/components/profile/Switch/style.module.scss.d.ts
  src/components/profile/index.ts
  src/components/store/HelpModal/index.tsx
  src/components/store/HelpModal/style.module.scss
  src/components/store/HelpModal/style.module.scss.d.ts
  src/lib/api/AuthAPI.ts
  src/lib/api/ResumeAPI.ts
  src/lib/api/UserAPI.ts
  src/lib/api/index.ts
  src/lib/config.ts
  src/lib/constants/socialMediaTypes.ts
  src/lib/hoc/withAccessType.ts
  src/lib/managers/AdminEventManager.ts
  src/lib/managers/AuthManager.ts
  src/lib/showToast.tsx
  src/lib/types/apiRequests.d.ts
  src/lib/types/apiResponses.d.ts
  src/lib/types/enums.ts
  src/lib/types/index.ts
  src/lib/utils.ts
  src/pages/profile.tsx
  src/pages/profile/edit.tsx
  src/pages/reset-password/[accessCode].tsx
  src/styles/pages/profile/edit.module.scss
  src/styles/pages/profile/edit.module.scss.d.ts
  src/styles/vars.scss
Labels: PR: Needs Review, PR: Good to Merge

#117 Implement profile page
  cypress/e2e/pages/edit-profile.cy.ts
  cypress/fixtures/profile.json
  cypress/support/commands.ts
  public/assets/icons/edit.svg
  public/assets/icons/email-solid.svg
  public/assets/icons/facebook-icon.svg
  public/assets/icons/github-icon.svg
  public/assets/icons/ig-icon.svg
  public/assets/icons/instagram.svg
  public/assets/icons/leaderboard-icon.svg
  public/assets/icons/link-icon.svg
  public/assets/icons/linkedin-icon.svg
  public/assets/icons/major-icon.svg
  public/assets/icons/profile-icon.svg
  public/assets/icons/twitter.svg
  src/components/common/GifSafeImage/index.tsx
  src/components/common/index.ts
  src/components/events/index.tsx
  src/components/home/Hero/style.module.scss
  src/components/layout/Navbar/style.module.scss
  src/components/leaderboard/LeaderboardRow/index.tsx
  src/components/leaderboard/TopThreeCard/index.tsx
  src/components/profile/Preview/index.tsx
  src/components/profile/Preview/style.module.scss
  src/components/profile/UserHandleNotFound/index.tsx
  src/components/profile/UserProfilePage/index.tsx
  src/components/profile/UserProfilePage/style.module.scss
  src/components/profile/UserProfilePage/style.module.scss.d.ts
  src/components/profile/index.ts
  src/lib/api/EventAPI.ts
  src/lib/api/UserAPI.ts
  src/lib/config.ts
  src/lib/constants/majors.json
  src/lib/constants/majors.ts
  src/lib/constants/ranks.ts
  src/lib/constants/socialMediaTypes.ts
  src/lib/types/apiResponses.d.ts
  src/lib/utils.ts
  src/pages/about.tsx
  src/pages/events.tsx
  src/pages/index.tsx
  src/pages/leaderboard.tsx
  src/pages/profile.tsx
  src/pages/profile/edit.tsx
  src/pages/register.tsx
  src/pages/u/[handle].tsx
  src/styles/pages/about.module.scss
  src/styles/pages/about.module.scss.d.ts
  src/styles/pages/profile/edit.module.scss
Labels: PR: Needs Review

#92 55 create store collections page
  src/lib/api/StoreAPI.ts
  src/pages/store/collection/[uuid].tsx
  src/styles/pages/store/collections.module.scss
  src/styles/pages/store/collections.module.scss.d.ts
Labels: PR: Needs Review

#128 Admin Event Page: Upload images along with Discord Event, implement generateACMURL
  src/components/admin/event/EventDetailsForm/index.tsx
  src/components/admin/event/ManageEventCard/index.tsx
  src/components/events/CalendarButtons/index.tsx
  src/lib/api/KlefkiAPI.ts
  src/lib/config.ts
  src/lib/managers/AdminEventManager.ts
  src/lib/types/apiRequests.d.ts
Labels: PR: Good to Merge

#130 Fix small CSS bug in user profile page
  src/components/profile/UserProfilePage/style.module.scss
Labels: PR: Needs Review

#132 Fix theme meta toggle, fix navbar padding
  src/components/common/ThemeToggle/index.tsx
  src/components/layout/Navbar/index.tsx
  src/components/layout/Navbar/style.module.scss
  src/components/layout/Navbar/style.module.scss.d.ts
Labels: PR: Needs Review

#131 Use scss vars in ThemeToggle
  src/components/common/ThemeToggle/style.module.scss
Labels: PR: Needs Review
